core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),

    path("__reload__/", include("django_browser_reload.urls")),
]


from django.conf import settings

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from .views import TodoList, TodoDetail, TodoDeleteView, TodoCreate, TodoUpdate

app_name="todo"

urlpatterns = [
    path("", TodoList.as_view(), name="list"),
    path("new/", TodoCreate.as_view(), name="create"),
    path("<int:id>/", TodoDetail.as_view(), name="detail"),
    path("<int:id>/delete", TodoDeleteView.as_view(), name="delete"),
    path("<int:id>/update", TodoUpdate.as_view(), name="update"),
]

todo/models.py
from django.db import models
from django.urls import reverse



class Todo(models.Model):

    STATUS_CHOICES = {
        "To Do":"To Do",
        "In Progress": "In Progress",
        "Completed":"Completed",
    }

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=128)
    content = models.TextField()
    status = models.CharField(choices=STATUS_CHOICES, max_length=11, default=STATUS_CHOICES["To Do"])


    def get_absolute_url(self):
        return reverse("todo:detail", kwargs={"id": self.id})
    
    def __str__(self) -> str:
        return self.title

todo/forms.py
from django import forms

from .models import Todo



class TodoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields["title"].widget.attrs.update({
            "class": "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-green-500 focus:border-green-500 block w-full p-2.5",
        })

        self.fields["content"].widget.attrs.update({
            "class": "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-green-500 focus:border-green-500 block w-full p-2.5",
        })
        self.fields["status"].widget.attrs.update({
            "class": "bg-gray-50 border border-gray-300 text-gray-900 text-md rounded-lg focus:ring-green-500 focus:border-green-500 block w-full p-2.5 ",
        })
    
    
    
    class Meta:
        model=Todo
        fields = ["title", "content", "status"]


    

todo/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from .models import Todo
from .forms import TodoForm

class TodoList(ListView):
    model = Todo
    template_name="todo_list.html"

    def get_queryset(self) -> QuerySet[Todo]:
        qs = super().get_queryset()
        search = self.request.GET.get("search")
        status = self.request.GET.get("status")

        if search != "" and search is not None:
            qs = qs.filter(title__icontains=search)
        if status != "" and status is not None:
            qs = qs.filter(status = status)
        return qs


class TodoDetail(DetailView):
    model = Todo
    pk_url_kwarg="id"
    template_name="todo_detail.html"


class TodoDeleteView(DeleteView):
    model = Todo
    pk_url_kwarg="id"
    template_name = "todo_delete.html"
    
    def get_success_url(self):
        return reverse_lazy('todo:list')

class TodoCreate(CreateView):
    model = Todo
    template_name = "todo_create.html"
    pk_url_kwarg="id"
    form_class=TodoForm

class TodoUpdate(UpdateView):
    model = Todo
    form_class=TodoForm
    pk_url_kwarg="id"
    template_name = "todo_update.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %} {% load tailwind_tags %}
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Django Todo</title>
        {% tailwind_css %}
    </head>
    <body class="min-h-screen">
        {% include "navbar.html" %}

        <div class="max-w-screen-xl flex flex-col justify-between mx-auto p-4">
            {% block content %} {% endblock content %}
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
    </body>
</html>

templates/navbar.html
{% load static %}
<nav class="bg-white border-gray-200 dark:bg-gray-900 dark:border-gray-700">
    <div
        class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4"
    >
        <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img
                src='{% static "django-icon.png" %}'
                class="h-8"
                alt="Flowbite
            Logo"
            />
            <span
                class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white"
                >Django Todo</span
            >
        </a>
        <button
            data-collapse-toggle="navbar-dropdown"
            type="button"
            class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
            aria-controls="navbar-dropdown"
            aria-expanded="false"
        >
            <span class="sr-only">Open main menu</span>
            <svg
                class="w-5 h-5"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 17 14"
            >
                <path
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M1 1h15M1 7h15M1 13h15"
                />
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-dropdown">
            <ul
                class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700"
            >
                <li>
                    <a
                        href= {% url "todo:create" %}
                        class="block py-2 px-3"
                        aria-current="page"
                        >Add Todo</a
                    >
                </li>
            </ul>
        </div>
    </div>
</nav>

todo/templates/todo_create.html
{% extends "base.html" %} {% block content %}
<div class="w-11/12 max-w-lg mx-auto">
    <div class="p-10 text-center space-y-4">
        <h2 class="text-4xl font-bold text-primary">Add Todo</h2>
        <h4>
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Consequuntur porro officiis dicta ipsa tenetur aliquid laborum,
            expedita, necessitatibus dolore voluptates enim sapiente doloribus
            suscipit itaque unde, optio cum excepturi similique.
        </h4>
    </div>
    <form method="POST">
        {% csrf_token %} {% for field in form %}
        <div class="mb-5">
            <label
                for="{{ field.id_for_label}}"
                class="block mb-2 text-sm font-medium text-gray-900"
                >{{field.label}}</label
            >
            {{field}}
        </div>

        {% endfor %}

        <input
            type="submit"
            value="Submit"
            class="text-white bg-primary hover:bg-primary-hover focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
        />
        <a
            type="button"
            value="Cancel"
            class="text-primary hover:text-primary-hover text-sm w-full font-medium sm:w-auto px-5 py-2.5 text-center"
            href='{% url "todo:list"  %}'
            >Cancel</a
        >
    </form>
</div>

{% endblock content %}

todo/templates/todo_delete.html
{% extends "base.html" %} {% block content %}
<div class="w-11/12 max-w-lg mx-auto">
    <div class="p-10 text-center space-y-4">
        <h2 class="text-4xl font-bold text-primary drop-shadow-lg">
            Delete Todo
        </h2>
    </div>
    <form method="POST" class="text-center space-y-4">
        {% csrf_token %}
        <h4 class="mb-5 text-lg w-full">
            Are you sure you want to delete todo with id: {{todo.id}} ?
        </h4>

        <h6 class="text-lg">
            Title: <span class="font-bold"> {{todo.title | upper}} </span>
        </h6>
        <div>
            <input
                type="submit"
                value="Submit"
                class="text-white bg-primary hover:bg-primary-hover focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
            />
            <a
                type="button"
                value="Cancel"
                class="text-primary hover:text-primary-hover text-sm w-full font-medium sm:w-auto px-5 py-2.5 text-center"
                href='{% url "todo:detail" id=todo.id  %}'
                >Cancel</a
            >
        </div>
    </form>
</div>

{% endblock content %}

todo/templates/todo_detail.html
{% extends "base.html" %} {% block content %}

<div class="space-y-6 mt-10">
    <div class="flex justify-between">
        <h1
            class="mb-4 text-4xl font-bold leading-none tracking-tight text-primary md:text-5xl lg:text-6xl"
        >
            {{todo.title}}
        </h1>

        <ul class="flex gap-4">
            <li>
                <a
                href= {% url "todo:update" id=todo.id %}
                    class="py-2.5 px-5 me-2 mb-2 text-sm font-medium text-primary focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-hover focus:z-10 focus:ring-4 focus:ring-gray-200"
                    >Edit</a
                >
            </li>
            <li>
                <a
                    href= {% url "todo:delete" id=todo.id %}
                    class="focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900"
                >
                    Delete</a
                >
            </li>
        </ul>
    </div>

    <p>
        Status:
        <span
            class="text-primary-hover ml-4 border border-primary font-medium rounded-lg text-sm w-full sm:w-auto px-4 py-2 text-center"
        >
            {{todo.status}}
        </span>
    </p>
    <p class="text-left border  min-h-[30vh] border-gray-100-100 py-4 rounded-lg text-gray-500">
        {{todo.content}}
    </p>
</div>

{% endblock content %}

todo/templates/todo_list.html
{% extends "base.html" %} {% block content %}

<div class="p-16 rounded-lg shadow-md bg-gray-200 mb-16 space-y-4 text-center">
    <h1
        class="mb-4 text-4xl font-bold leading-none tracking-tight text-primary md:text-5xl lg:text-6xl"
    >
        Django Flowbite Project
    </h1>
    <p
        class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48"
    >
        This is a todo list project built using django, tailwind and flowbite
        components.
    </p>
</div>

<div
    class="p-4 bg-neutral-200 rounded-md text-center tracking-wider font-bold text-primary text-xl"
>
    TODO LIST
</div>

<form class="my-4">
    <label
        for="default-search"
        class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white"
        >Search</label
    >
    <div class="flex gap-4">
        <input
            type="search"
            id="default-search"
            class="block w-7/12 p-4 ps-10 text-md text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500"
            placeholder="Search title..."
            name="search"
        />

        <select
            name="status"
            class="block p-4 ps-10 text-md text-gray-900 border w-3/12 border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500"
        >
            <option value="" selected>Select Status</option>
            <option value="To Do">To Do</option>
            <option value="In Progress">In Progress</option>
            <option value="Completed">Completed</option>
        </select>
        <button
            type="submit"
            class="text-white end-2.5 w-2/12 bottom-2.5 bg-primary hover:bg-primary-hover focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-md px-4 py-2"
        >
            Search
        </button>
    </div>
</form>

<div
    class="grid grid-cols-1 justify-items-center md:grid-cols-2 lg:grid-cols-3 gap-4"
>
    {% for todo in object_list %}

    <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow">
        <a href="{{todo.get_absolute_url}}">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">
                {{todo.title}}
            </h5>
        </a>
        <p class="mb-3 font-normal text-gray-700">
            {{todo.content | truncatechars:100}}
        </p>
        <a
            href="{{todo.get_absolute_url}}"
            class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-primary rounded-lg hover:bg-primary-hover focus:ring-4 focus:outline-none focus:ring-green-300"
        >
            Read more
            <svg
                class="rtl:rotate-180 w-3.5 h-3.5 ms-2"
                aria-hidden="true"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 14 10"
            >
                <path
                    stroke="currentColor"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M1 5h12m0 0L9 1m4 4L9 9"
                />
            </svg>
        </a>
    </div>

    {% empty %}
    <div
        class="w-full col-span-full p-16 text-center bg-white border border-gray-200 rounded-lg shadow"
    >
        No todos found.
    </div>

    {% endfor %}
</div>
{% endblock content %}

todo/templates/todo_update.html
{% extends "base.html" %} {% block content %}
<div class="w-11/12 max-w-lg mx-auto">
    <div class="p-10 text-center space-y-4">
        <h2 class="text-4xl font-bold text-primary drop-shadow-lg">
            Update Todo {{todo.id}}
        </h2>
    </div>
    <form method="POST">
        {% csrf_token %} {% for field in form %}
        <div class="mb-5">
            <label
                for="{{ field.id_for_label}}"
                class="block mb-2 text-sm font-medium text-gray-900"
                >{{field.label}}</label
            >
            {{field}}
        </div>

        {% endfor %}

        <input
            type="submit"
            value="Submit"
            class="text-white bg-primary hover:bg-primary-hover focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
        />
        <a
            type="button"
            value="Cancel"
            class="text-primary hover:text-primary-hover text-sm w-full font-medium sm:w-auto px-5 py-2.5 text-center"
            href='{% url "todo:detail" id=todo.id  %}'
            >Cancel</a
        >
    </form>
</div>

{% endblock content %}